#!/bin/bash

smartctl -t long /dev/sda > /dev/null
smartctl -t long /dev/sdb > /dev/null
smartctl -t long /dev/sdb > /dev/null

sleep 300m

smartctl -H /dev/sda
smartctl -H /dev/sdb
smartctl -H /dev/sdc
