#!/bin/bash

thresh=90
log="$(mktemp)"
first_disk=true

declare -a disks=(
    /
    /var
    /home
    /mnt/grab
    /mnt/data
)

for disk in "${disks[@]}"; do
    space_used=$(df -h --output=pcent "$disk" | tail -n1 | sed 's/ //g' | sed 's/%//')

    if [ "$space_used" -gt "$thresh" ]; then
        mnt_point="$(grep " $disk " /proc/mounts | cut -d ' ' -f1)"

        "$first_disk" && echo "FILESYSTEM       (=) USED      FREE (-) %USED AVAILABLE     TOTAL MOUNTED ON" >> "$log"

        dfc -p "$mnt_point" | tail -n1 >> "$log"
        first_disk=false
    fi
done

gpg --yes --quiet --no-tty -e -a --batch \
    -r 0xA03A50C0C71BE6BE \
    "$log"

"$HOME"/scripts/maillog "daemon@keks" \
                        "Diskspace" \
                        "daemon@tribly.de" \
                        "" \
                        "$log.asc"

trap 'rm $log $log.asc' EXIT TERM
