#!/bin/bash

dir="/home/$(whoami)/blog"
push=""

if [ "$PWD" != "$dir" ]; then
    cd "$dir"
fi

###
# Check if we have uncommit stuff
###
if [ "$(git status --porcelain)" ]; then
    echo "Uncommited stuff, exiting."
    exit
fi

###
# Check if we have unpushed stuff
###
if [ "$(git log --pretty=oneline origin/master..master)" ]; then
    git log --pretty="format:%p %s" origin/master..master
    echo -n "Unpushed commits. Push them? [y/n] "
    read push
fi

###
# Check if we have drafts left we forgot to publish
###
if [ "$(ls -A _drafts)" ]
then
    got_drafts=true
else
    got_drafts=false
fi

if "$got_drafts"; then
    echo "Found drafts"

    for x in _drafts/*
    do
        echo -n "Want to publish "$(basename $x)"? [y/n]: "
        read choice
        if [ "$choice" == "y" ]; then
            echo "--------------------"
            echo "Publishing posts"
            echo "--------------------"
            mv "$x" _posts
            git add -A .
            git commit -m "Publishing $x"
        fi
    done
fi

# Push, after we published the post
if [ "$choice" == "y" ]; then
    echo "--------------------"
    echo "Pushing to repo"
    echo "--------------------"
    git push origin master
fi

echo "--------------------"
echo "Building site"
echo "--------------------"
jekyll build

echo "--------------------"
echo "Pushing the changes"
echo "--------------------"
rsync --human-readable -a --info=progress2 --partial \
    _site/ uberspace:blog
