#!/bin/bash

DIR="/home/$(whoami)/blog"

if [ "$PWD" != "$DIR" ]; then
    cd $DIR
fi

###
# Check if we have uncommit stuff
###
if [ $(git status --porcelain) ]; then
    echo "Uncommited stuff, exiting."
    exit
fi

###
# Check if we have unpushed stuff
###
if [ "$(git log --pretty=oneline origin/master..master)" ]; then
    git log --pretty="format:%p %s" origin/master..master
    echo "Unpushed commits. Push them? [y/n] "
    read choice
    if [ $choice == "y" ]; then
        git push origin master
    fi
fi

###
# Check if we have drafts left we forgot to publish
###
if [ "$(ls -A _drafts)" ]
then
    got_drafts=true
else
    got_drafts=false
fi

if $got_drafts; then
    echo "Found drafts"

    for x in _drafts/*
    do
        echo -n "Want to publish $(basename $x)? [y/n]: "
        read choice
        if [ $choice == "y" ]; then
            mv "$x" _posts
        fi
    done
fi

jekyll build

rsync --human-readable -a --info=progress2 --partial \
    _site/ uberspace:blog
