#!/bin/bash

destination="/mnt/grab/movies/"
sourcef="/home/$(whoami)/torrents/"
expression="{n.space('_').lower()}/{n.space('_').lower()}"

filebot -rename \
    --db TheMovieDB \
    -r \
    -non-strict \
    --format "$destination$expression" $sourcef
