#!/bin/bash

destination="/mnt/grab/series/"
sourcef="/home/$(whoami)/torrents/"
expression="{n.space('_').lower()}/season_{s}/{n.space('_').lower()}_{s00e00}_{t.space('_').lower()}"
TMP_F=$(mktemp)

filebot -rename \
    --db TheTVDB \
    -r \
    -non-strict \
    --format "$destination$expression" $sourcef | sponge /tmp/series_move.log

sed 's/\[MOVE\] Rename \[\/home\/heinz\/torrents\//\n/' /tmp/series_move.log | sed 's/ to /\n/' | sed 's/\[\/mnt\/data\///'

tree $destination -L 2 -d -C --nolinks -T "" -H mhm -o $TMP_F

sed -i "/BODY/ a\
    html { display: table; margin: auto}\n \
    body { display: table-cell; vertical-align: middle}" $TMP_F

chmod 644 $TMP_F

rsync --human-readable -a --info=progress2 --partial $TMP_F uberspace:html/la

rm $TMP_F

